### ISSUE TITLE
New filter: overpass query

### ISSUE THREAD

**Issue by yopaseopor** [mapbox/osmcha-frontend#151]
As a mapper of OSM I use and know something about  http://www.overpass-turbo.eu . I think it would be interesting to add the possibility to filter by overpass query, which would make the tool extremely exact to check specific kind of nodes, relations and ways.

**Comment by kepta** [comment]
This sounds great @yopaseopor, @willemarcel thoughts ?

**Comment by willemarcel** [comment]
It's a good idea, but I don't see a way to implement it... We don't have all OSM features in the OSMCha database, so we could only search in the suspicious features that we have. A problem is that we don't know if a feature that we have in our database is the most updated version, so the query could return a result with features that are not updated or doesn't exist any more.

As overpass doesn't return the feature version and the id of the last changeset that modified it, we cannot use it to get the data to query for features and changesets in osmcha.

**Comment by yopaseopor** [comment]
I would see as one filter more, using the most updated data. People use OSMcha can know these limitations. Overpass is a "query language" well known for the OSM community and would be the best filter to find something specific in OSM. Also...Are you telling us your statistics and filters are based in not updated OSM data?? Are you telling us OSMCha is not reliable? I thank and saw OSMCha with calendar things, etc... so is this not truth?? What a disappointment :( 👎

**Comment by planemad** [comment]
@yopaseopor it would be great if you could describe your use case for an overpass filter. How would you use such a feature?

**Comment by yopaseopor** [comment]
Nowadays in Spain we are so near of big agreements with official
adminsitrations to use their data inside OSM. One of these big tags would
be the levels of a building. So , for example I would try to find if any
people has change something about building levels in a specific zone , to
keep the stability and the realibility of the data.

With overpass...you can ever find nearly whatever you want. For example,
I'm also an enthuthiastic of traffic signs. With overpass I can find ...all
the traffic signs in a road. http://overpass-turbo.eu/s/qj5
So with this feature in OSMCha I would review an specific element (with its
code) around the country, around the world.

For me overpass is the method to find specifically some kind of item inside
the big database is OSM. And OSMCha would be the perfect tool to review it.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by willemarcel** [comment]
Hi @yopaseopor,

:)

> Are you telling us your statistics and filters are based in not updated OSM data?? Are you telling us OSMCha is not reliable?

We have all changesets since we begin to use OSMCha, but we don't have all the OSM features (nodes, ways, relations). The features we have in our database are the ones that [osm-compare](https://github.com/mapbox/osm-compare) consider as suspicious/wrong and each feature are listed in the changeset page that created/updated it.

As we don't delete old features, if a user fixes an error in a feature and it is not more considered as suspicious/wrong, it will continue in the osmcha database (with the osm version information).

The use cases that you described can be handled with https://github.com/osmlab/changewithin. You can also add a `changed` [param](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_date_of_change_.28changed.29) to your overpass query and get only the objects that were modified since your last review.

Thank you very much for your suggestion!
