### ISSUE TITLE
Option to mark some changeset to "don't want to say good or bad"

### ISSUE THREAD

**Issue by yopaseopor** [mapbox/osmcha-frontend#152]
As a mapper of a determined zone I can say if a changeset is good or bad...but of some changesets I have...doubts but I can't mark it . I wish a "not reviewed but known" or "doubt" option.

**Comment by willemarcel** [comment]
It could be done by adding a tag. @kepta what do you think about to change the interface to allow the user to add tags before the review?

**Comment by kepta** [comment]
@willemarcel 
As you said, decoupling tags and reviewing, would greatly simplify a lot of our current workflow problems.
This would unblock https://github.com/mapbox/osmcha-frontend/issues/149

@planemad @manoharuss ?

**Comment by planemad** [comment]
👍 for being able to add tags without a a review. This essentially seems like something like "Request a review" where either a mapper or a reviewer can flag certain changesets to get it more eyes on it.

**Comment by manoharuss** [comment]
👍  for "Request a review"

**Comment by kepta** [comment]
This sounds great, will go ahead and do the needful.

**Comment by rasagy** [comment]
We must be clear with the goal for **tags**: Are they to add more metadata to a _changeset_ or to a _review_?

From one of the comment from #149:
>Clearing of a review probably means that the initial review was probably mistaken and needs to be changed (or the initial impression is not right anymore). So the tag's get outdated when the review is cleared.

Looking at the current list of tags, all of them are relevant to a changeset that has been marked 👎 :
![screenshot 2017-07-11 16 47 32](https://user-images.githubusercontent.com/1117531/28065981-ae9193a2-6658-11e7-9846-ea1c486983aa.png)

Decoupling and showing tags & review buttons all the time means that you can see the above tags (and add) without reviewing a changeset — which might lead to confusion + extra steps to remove these tags as highlighted in #149.

If we see value in adding more tags such as `Request a review` that might not apply to a 👎  changeset, then we should explore separating tags based on the type of review:
- Tags for changesets marked harmful 👎 : `Severity`, `resolution`, `intent` etc.
- Tags for changesets that aren’t marked: `Request a review`
- Tags for changesets marked good 👍 : ?
- Tags for all changesets (irrespective of review): ?

----

If this seems like diving too much into a scenario that might not be very common, we can revisit the idea of marking a changeset as `❓ Unsure/Ask for review` instead of 👍 /👎  — Ideally you would expect someone else to check❓ changeset and mark it as 👍 /👎  instead of doing both review + removing the tag.

PS: This also means that someone will be able to update tags and review added by another user — and we’ll have to make this conditional (you can only remove a tag till the changeset has not been reviewed or you can only review a changeset marked ❓, but not 👍 /👎 )

I’ll spend some time later this week, but happy to hear more thoughts on this before I take a stab at it — @kepta let’s hold on implementing this till we’re sure if this implementation is solving the use case that @yopaseopor highlighted.

cc

**Comment by willemarcel** [comment]
@rasagy Your considerations are very relevant. I specially like the idea of separating the tags by use cases.

> Tags for changesets marked good 👍 : ?

I feel the necessity of a tag to say that a changeset is not harmful, but contains some not drastic errors. Currently I'm marking as good and adding `Severity: Low` and `Resolved`. 

> PS: This also means that someone will be able to update tags and review added by another user — and we’ll have to make this conditional (you can only remove a tag till the changeset has not been reviewed or you can only review a changeset marked ❓, but not 👍 /👎 )

Right now the API allows any user to add and remove tags while the changeset is not reviewed. After the review, only the user that reviewed it or a staff user can change the tags or the review status.

**Comment by SwiftFast** [comment]
Perhaps "good" needs to be split. Sometimes I want to say "I skimmed it and it looks sane, but I haven't visited the area and/or checked thoroughly", and sometimes I want to say "I am sure it's all good".

It saves time - skimmers don't have to re-check what I just skimmed. But someone with better knowledge of the area wouldn't be led to believe it's all good and would check it thoroughly.

**Comment by tridip1931** [comment]
Stale, closing this. There are lots of good feedback above. Putting to backlog for now.
