### ISSUE TITLE
User name breaks in Arabic

### ISSUE THREAD

**Issue by kepta** [mapbox/osmcha-frontend#156]
https://osmcha.mapbox.com/changesets/50179818

The username get jumbled in the above changeset.

**Comment by kepta** [comment]
@tridip1931 can you take a look at this?

**Comment by tridip1931** [comment]
The issue seems to be related to chrome & safari.

_Safari_
<img width="1261" alt="screenshot 2017-08-28 15 41 09" src="https://user-images.githubusercontent.com/7458983/29769282-596b55b4-8c07-11e7-8656-4f3da9a11430.png">


_Chrome_
<img width="1379" alt="screenshot 2017-08-28 15 42 11" src="https://user-images.githubusercontent.com/7458983/29769323-80bace42-8c07-11e7-9af8-3cb76b47cfe2.png">


But it worked totally fine in firefox

_Firefox_
<img width="1282" alt="screenshot 2017-08-28 15 43 09" src="https://user-images.githubusercontent.com/7458983/29769358-9f7b6de6-8c07-11e7-932b-283ae1afd4a8.png">

---
The reason for this break may be due to default browser styles for different languages.

For now I have added `dir="ltr"` in the anchor tag. This seems to solve the issue.
