### ISSUE TITLE
Tag dropdown is hidden by changeset-map details

### ISSUE THREAD

**Issue by planemad** [mapbox/osmcha-frontend#161]
Cannot access all the tags in the list.

<img width="303" alt="screen shot 2017-07-19 at 11 42 26 am" src="https://user-images.githubusercontent.com/126868/28353053-77a48726-6c77-11e7-817b-cc09f525b72a.png"><br>
[changeset](https://osmcha.mapbox.com/changesets/50392986?filters=%7B%22date__gte%22%3A%5B%7B%22label%22%3A%22%22%2C%22value%22%3Anull%7D%5D%2C%22users%22%3A%5B%7B%22label%22%3A%22Tinkerbell9597%22%2C%22value%22%3A%22Tinkerbell9597%22%7D%5D%7D)

cc @rasagy

**Comment by kepta** [comment]
@tridip1931 you think you can take this one?

**Comment by tridip1931** [comment]
@kepta @planemad I am not aware what the issue is? Do I have to put scroll in the dropdown for smaller windows? In the live version I am able to see all the options.

<img width="214" alt="screenshot 2017-08-28 14 49 11" src="https://user-images.githubusercontent.com/7458983/29767451-1e5ea6da-8c00-11e7-9a95-1e15479f3381.png">

**Comment by kepta** [comment]
@tridip1931 this happens when you select a feature and the feature table hides the dropdown.
You can see that happening in @planemad 's screenshot.

To reproduce,
1. Decrease the window height 
2. Select a feature on map, (this should bring the table on the lower left)
3. Click on tags to get drop down.

**Comment by planemad** [comment]
@tridip1931 yup, this looks fixed! The menu would previously go under the changeset map infoboxes.

<img width="405" alt="screen shot 2017-08-28 at 2 51 31 pm" src="https://user-images.githubusercontent.com/126868/29767536-6ba72002-8c00-11e7-88ae-4e066f4af2c7.png">
