### ISSUE TITLE
feature request - reviewer's comment

### ISSUE THREAD

**Issue by govvin** [mapbox/osmcha-frontend#248]
## *Brief Description*
It would be really nice if it would be possible for the reviewer to add text, to elaborate on their review, within OsmCha.

## What is the motivation / use case for this feature?
Improve/make more useful the comment left on the changeset.
![image](https://user-images.githubusercontent.com/5821688/34753541-9aa5cf0e-f5f3-11e7-8243-10b920d53b2a.png)

## What  is the current behaviour, (attach relevant screenshots) ?
Reviewer may add a separate comment.

## What  is the expected behaviour ?
More useful, hopefully helpful comment/review notes.

## When does this occur ?
When reviewing changesets.

**Comment by willemarcel** [comment]
Thanks, @govvin! I believe I can dedicate some time soon to make this possible.

**Comment by govvin** [comment]
Awesome!

There's feedback in the [mailing list](https://lists.openstreetmap.org/pipermail/talk/2018-January/080006.html) about this feature. You might want to check it out. -- Some aren't too happy about it.

**Comment by rasagy** [comment]
Expanding @govvin’s ticket to summarize the feedback seen on the mailing list + internal discussions:

1. Allow user to decide if they want to use this feature when they see the announcement _(Default opt-in since comments **will not** be posted automatically)_
2. Allow user to modify the template messages(s) _(This will enable the reviewer to use local language/change style of the default message)_
3. Once you validate (:+1:/:-1:) — open the Discussions panel, pre-fill the comment text using the template, and give the user control to actually post a comment _(Allows the reviewer to modify before posting)_

@willemarcel has been working on improving this feature. @willemarcel @tridip1931 & I did a quick brainstorming on how to approach this, I’m sharing initial sketches from the discussion:

## 1. Settings for comment + editable template:

This could be added in the profile/settings section, allowing user to choose if they want to use this feature, and if yes edit the template messages for 👍 & 👎.

![img_20180116_172904_01](https://user-images.githubusercontent.com/1117531/34996819-c98cacb8-fb00-11e7-8e2e-3820af6a2e83.jpg)

## 2. Workflow that allows the reviewer to have control on the comment posting action:

Once a changeset is reviewed, the discussion panel will open with the template message (if the setting is switched to `yes`), and the message will be posted _only_ if the reviewer decides to.

![img_20180116_173432_01](https://user-images.githubusercontent.com/1117531/34997012-4ceeaed0-fb01-11e7-8e33-44cbc93cf5be.jpg)

I’m hoping this takes care of the major issues, and we will continue to listen to the feedback from the community to get this feature right. :)

**Comment by westnordost** [comment]
Or, as a first step, only step 2 of @rasagy's suggestion. After clicking good or bad, prefill an input box with the template text. This is especially useful if the user clicked on "bad", because then he will want to explain what is the problem there. Just saying "this is bad, contact me" might come across as rude.

(I also find the template a bit verbose for an automatically created message, but I should perhaps create another issue for that)

**Comment by govvin** [comment]
Would it be possible to change the terms used? "Good", obviously, wouldn't have any negative connotation, but with a "bad" changeset review, many users may become defensive or agitated. (I've encountered some.)

Perhaps, "needs improvement", "unsatisfactory", or "non-standard"?

**Comment by willemarcel** [comment]
> After clicking good or bad, prefill an input box with the template text and let the user (re-)write it.

@westnordost in the first image that @rasagy posted, we have the option to the user activate the feature you're suggesting.

@govvin good point! I'm not sure about the best word, what do you think about "faulty" or "defective? "needs improvement" can be imprecise to vandalism changesets... "unsatisfactory" is good, but I'd prefer a simpler and more direct word

Thanks, guys!

**Comment by westnordost** [comment]
I wouldn't throw vandalism changesets into one pot (=one UI button) with well-meant changesets that are somehow faulty.

Should this OsmCha feature also cover vandalism changesets? I would think that vandalism is simply reverted and not discussed.

**Comment by willemarcel** [comment]
@westnordost I understand that @govvin was talking about the word we use not only in the changeset comments, but also in the `Verify` button. Although we don't need to comment vandalism changesets, it's useful to have them reviewed in OSMCha.

**Comment by govvin** [comment]
"faulty" may still be a loaded word. How about sub-optimal? I'm sure there's a simpler, more constructive term to use out there.

**Comment by willemarcel** [comment]
We deployed a new version this week that solves this issue. Although we want to make an improvement (https://github.com/mapbox/osmcha-frontend/issues/259) yet.
