### ISSUE TITLE
I can not access OSMCHA

### ISSUE THREAD

**Issue by adiatmad** [mapbox/osmcha-frontend#299]
## *I can not open https://osmcha.mapbox.com/ from my Chrome on Windows*

![capture](https://user-images.githubusercontent.com/38268616/42446556-f6c8ec9a-83a0-11e8-93b7-b6aa0cf8fa40.JPG)

## Please tell us about your environment:
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

## Other Information / context:
I can open using private mode

**Comment by batpad** [comment]
@adiatmad can you confirm if this issue is reliably reproducible? Do you face the same issue in any other browser? I am unable to reproduce on Chrome + Ubuntu.

Since it works in private mode, can I ask you to try disabling any browser add-ons and see if that makes it work? If you "hard reload" the page with like ctrl-shift-R does it work?

This sounds pretty weird, but possibly some interesting edge case - if you are still facing this issue, let know, I can try finding a windows machine to try and reproduce this on.

**Comment by willemarcel** [comment]
Hi @adiatmad!

I believe you tried to access OSMCha while we were updating our system, so your browse cached this nginx page. Could you try to delete the osmcha cache? Instructions: https://7labs.io/tips-tricks/clear-site-specific-cookies-cache.html#Clear_site-specific_cookies_and_cache_in_Chrome

**Comment by adiatmad** [comment]
@batpad @willemarcel I try to your suggestion and succeed by prevent osmcha to save cookies. It works. Thank you.

**Comment by willemarcel** [comment]
All issues with OSMCha have been solved. If you yet see some error, just reload the page.
