### ISSUE TITLE
Ignore changesets with no affected nodes within bbox

### ISSUE THREAD

**Issue by Skippern** [mapbox/osmcha-frontend#347]
## *Brief Description*
When monitoring changes in a restricted area (i.e., one county), there comes up a lot of changesets with extremely large affected areas, where closest altered object can be hundreds of kilometer away from monitored area. This becomes SPAM that often leads to flagging good/bad without having knowledge about the areas actually affected.

## What is the motivation / use case for this feature?
Less noise in my filters, less false possitives/negatives.

**Comment by willemarcel** [comment]
Hi @Skippern !

Thanks for your suggestion and thank you very much for being one of the most active OSMCha users!!!

Take a look on the **BBox size bound** field on the [filters page](https://osmcha.mapbox.com/filters). It allows you to filter changesets that have a bbox area lower than `X` times the area of your BBox or geometry filter. For example, if the geometry you defined in your filter has an area of 1 degree and you set the **BBox size bound** to 2, it will filter the changesets whose bbox area is lower than 2 degrees.

That is the solution we found to that problem, because we don't register all features geometries in our database.

**Comment by Skippern** [comment]
The problem isn't the size of the BBOX, but rather that when selecting a BBOX for i.e. the state of Espírito Santo, I get filtered hits with no changed objects within the state of ES, or even none in Brazil, but stretching from Chile to Vietnam. I would like to ignore those changesets that have no edited objects  within ES even when their BBOX stretches multiple continents.

**Comment by willemarcel** [comment]
Yes, I know it. We can't do it because we don't store all features in our database (it would be much more complex and expensive to query changesets considering all its features). But if you set a BBOX size bound to a 3, for example, it will exclude those types of changesets from your filter. The bbox size bound is relative to the size of your geometry/bbox, so if you defined the geometry of ES in the filter, it will get only the changesets whose bbox is not bigger than 3x the area of ES.

Make some tests and you'll confirm that it helps a lot. :smiley:

**Comment by Skippern** [comment]
Trying it out 👍

**Comment by vgeorge** [comment]
Nice, I was looking for a way to filter large area changesets too.

**Comment by zyphlar** [comment]
It might be unclear but AFAIK the BBox size bound filter is a customizable "huge bbox" flag. "Filter changesets smaller than X times your bbox" is a less clear way of saying "only show changesets X times bigger than your filter's bounding box" aka you choose whether you want to exclude city, state, country, or world-spanning changesets from your filter.

@willemarcel adjusting the wording of the GUI label might help here. I came searching around github for this feature because I didn't understand the "Filter changesets that have a bbox area lower than X times the area of your BBox" language. Osmcha seems to say "filter" as in "only include in results" but filter can also more commonly mean "exclude from results" as in "spam filter" or "filter out impurities." Maybe globally replacing the verb filter with "include/exclude" as appropriate will be more clear, and the noun filter (https://osmcha.org/filters*) can remain for the search functionality itself.

**Comment by georg-d** [comment]
>  I came searching around github for this feature because I didn't understand the "Filter changesets that have a bbox area lower than X times the area of your BBox" language. [...] replacing the verb filter with "include/exclude" as appropriate will be more clear, and the noun filter (https://osmcha.org/filters*) can remain for the search functionality itself.

+1 

The change https://github.com/mapbox/osmcha-frontend/issues/657 is probably visible as of today. Still, I did not understand from the GUI (label and pop up help text) and from documentation. I had to read several issues here to understand. For me, "filter" does not tell whether the desired stuff is what passes (think coffee filter) or what remains (think mature fish are catched in a net while baby fish pass). Both "exclude/include" as suggested above or "ignore changesets whose..." of https://github.com/mapbox/osmcha-frontend/issues/173#issuecomment-320647106 would be 100% clear to me. Text idea:

> Exclude changesets whose area is lower than X times the area of your BBox or geometry filter. For example, if the geometry you defined in your filter has an area of 1 degree and you set the 'Changeset size bound' to 2, the changesets whose area is lower than 2 degrees will be ignored.

**Comment by arjunaraoc** [comment]
"Ignore changesets whose... "  text mentioned in https://github.com/osmus/osmcha-frontend/issues/173#issuecomment-320647106  is better.
