### ISSUE TITLE
Add redirect from https://www.osmcha.org/ to non-www

### ISSUE THREAD

**Issue by tordans** [mapbox/osmcha-frontend#441]
If I call https://www.osmcha.org/, I get a `DNS_PROBE_FINISHED_NXDOMAIN`.
IMO, this should be a redirect to https://osmcha.org/.

**Comment by artyomnov** [comment]
@tordans ✋ The redirect is already setup. Please check it https://www.osmcha.org/. Thank you for a good catch!

**Comment by batpad** [comment]
> Please check it https://www.osmcha.org/. Thank you for a good catch!

This does not quite seem to work for me. While the page loads at https://www.osmcha.org, logging in does not work.

Ideally, any request to https://www.osmcha.org would return a 301 Redirect to https://osmcha.org, so that there is a single domain being used for the application (I imagine using multiple domains could cause issues with the OAuth callbacks, etc. and doing a 301 redirect rather than serving the same content from the two different domains is probably a better idea here).

**Comment by artyomnov** [comment]
@batpad Have you tried to login one more time? I can't reproduce any issues with this part of app.

**Comment by willemarcel** [comment]
@artyomnov I had the same problem as @batpad, I think he is right about not serving the application on two domains.

**Comment by tordans** [comment]
Right now, it is not a redirect. It should, however, be a 301-redirect from www.* to non-www.

To reproduce: 
1. https://www.osmcha.org/
2. click login => window shows
3. in window: login
4. window shows a blank page at `https://osmcha.org/oauth-landing.html?oauth_token=###&oauth_verifier=###`

```
$ http https://www.osmcha.org
HTTP/1.1 200 OK
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 604
Content-Type: text/html; charset=utf-8
Date: Thu, 09 Apr 2020 04:43:50 GMT
ETag: W/"55dffc9d3489bd307502f80093bf0148"
Server: nginx/1.10.3 (Ubuntu)
Vary: Origin, Accept-Encoding
X-Frame-Options: SAMEORIGIN

<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta name="google" value="notranslate"><link rel="shortcut icon" href="https://osmcha.org/favicon.ico"><link rel="preconnect" href="https://osmcha-django-staging.tilestream.net"><title>OSM Changeset Analyzer</title><script type="text/javascript">"http:"==location.protocol&&(location.href=location.href.replace(/^http:/,"https:")),function(o){if(console.log(o.host.indexOf("github.io")),o.search&&-1<o.host.indexOf("github.io")){var t={};o.search.slice(1).split("&").forEach(function(o){var i=o.split("=");t[i[0]]=i.slice(1).join("=").replace(/~and~/g,"&")}),void 0!==t.p&&window.history.replaceState(null,null,o.pathname.slice(0,-1)+(t.p||"")+(t.q?"?"+t.q:"")+o.hash)}}(window.location)</script><link href="https://osmcha.org/static/css/main.0be1178e.css" rel="stylesheet"></head><body><div id="root"></div><script type="text/javascript" src="https://osmcha.org/static/js/main.f91c9351.js"></script></body></html>

$ http https://osmcha.org
HTTP/1.1 200 OK
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 604
Content-Type: text/html; charset=utf-8
Date: Thu, 09 Apr 2020 04:43:58 GMT
ETag: W/"55dffc9d3489bd307502f80093bf0148"
Server: nginx/1.10.3 (Ubuntu)
Vary: Origin, Accept-Encoding
X-Frame-Options: SAMEORIGIN

<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><meta name="google" value="notranslate"><link rel="shortcut icon" href="https://osmcha.org/favicon.ico"><link rel="preconnect" href="https://osmcha-django-staging.tilestream.net"><title>OSM Changeset Analyzer</title><script type="text/javascript">"http:"==location.protocol&&(location.href=location.href.replace(/^http:/,"https:")),function(o){if(console.log(o.host.indexOf("github.io")),o.search&&-1<o.host.indexOf("github.io")){var t={};o.search.slice(1).split("&").forEach(function(o){var i=o.split("=");t[i[0]]=i.slice(1).join("=").replace(/~and~/g,"&")}),void 0!==t.p&&window.history.replaceState(null,null,o.pathname.slice(0,-1)+(t.p||"")+(t.q?"?"+t.q:"")+o.hash)}}(window.location)</script><link href="https://osmcha.org/static/css/main.0be1178e.css" rel="stylesheet"></head><body><div id="root"></div><script type="text/javascript" src="https://osmcha.org/static/js/main.f91c9351.js"></script></body></html>
```

**Comment by artyomnov** [comment]
@tordans @batpad @willemarcel This issue is about problem with DNS, to solve it I've reconfigured DNS settings via AWS Route53. As you know, DNS protocol doesn't support any status codes, so it's impossible to setup redirect on DNS level. I think we should change some oauth settings in the osmcha app.

**Comment by batpad** [comment]
> As you know, DNS protocol doesn't support any status codes, so it's impossible to setup redirect on DNS level.

Yes, the redirect cannot be done at the DNS level because DNS does not have a concept of status codes.

The way this is generally done:

 - You create a CNAME record that points from www.example.com to example.com
 - On your webserver (apache, nginx, etc.) you check for requests to www.example.com/* and return a 301 redirect to redirect to example.com/*

The directive in `nginx` should look something like this:

```
server { server_name www.example.com; return 301 $scheme://example.com$request_uri; }
```

In general, it is considered good practice to redirect either all www to non-www or non-www to www and not serve the same content on what search engines essentially consider two separate domains. This is generally pretty well known configuration on the webserver end and should hopefully be straightforward to setup in nginx settings. Sorry if my previous comment seemed to suggest this should be done at the DNS-level.

I would strongly recommend against trying to change the oauth settings to try and support a non-standard approach of having two domains point to the same site - you will likely run into other issues if you do this.

**Comment by tordans** [comment]
In case configuring the webserver is not the right approach hiere, we could always redirect in JavaScript (like is done for http-to-https already). I prepared a PR at https://github.com/mapbox/osmcha-frontend/pull/448 (and hinted at the non-existing SEO issues there).

**Comment by artyomnov** [comment]
@batpad @tordans I know about this kind of configuration in web servers (nginx, apache, etc), but in the current configuration of osmcha app we don't have any of them. We have only DNS recordset in Route 53 and custom mapbox ECS service, on which both FE and BE run. I can't apply redirect settings for this custom ECS service, because it just doesn't support them.

**Comment by artyomnov** [comment]
@batpad @tordans I'll try to add www to oauth url, probably it should help
https://github.com/mapbox/osmcha-django/issues/253

**Comment by batpad** [comment]
> I prepared a PR at #448 (and hinted at the non-existing SEO issues there).

The frontend redirect seems like a totally viable workaround to me :+1: . Completely agree that the SEO issue here does not exist since content is behind a login anyway :+1:

**Comment by tordans** [comment]
> @batpad @tordans I'll try to add www to oauth url, probably it should help
> [mapbox/osmcha-django#253](https://github.com/mapbox/osmcha-django/issues/253)

I think the goal has to be to have _one_ domain, so just www. or non-www. Changing the oauth config does not reach this goal.

> I've redeployed with www oauth url and it runs into issues to login via just `osmcha.org`

Nothing changed for me: I can login no the non-www but not login on the www version of the app.

**Comment by tordans** [comment]
The JS-Redirect is live and working; I think we can close this issue. Thank you all!
