### ISSUE TITLE
Filter Issue

### ISSUE THREAD

**Issue by adiatmad** [mapbox/osmcha-frontend#661]
Hello, I'm facing an issue with my [filter](https://osmcha.org/filters?aoi=52a964ee-5c84-4a5c-815a-48c26bcac276). It's only showing one changeset, it should display more changesets, just like [this one](https://osmcha.org/changesets/136091725/). Do you have any idea what's going wrong with my filter? Thanks for your help

**Comment by willemarcel** [comment]
Hi @adiatmad ! In order to save some space on the database, we don't register all the features' tags in created and deleted features, but only the main one (amenity, landuse, highway, building...). When a feature is modified, though, we register all tag changes.

However, in that case, I believe you can get good results searching by the [source of the changeset](https://osmcha.org/filters?filters=%7B%22date__gte%22%3A%5B%7B%22label%22%3A%222023-05-01%22%2C%22value%22%3A%222023-05-01%22%7D%5D%2C%22source%22%3A%5B%7B%22label%22%3A%22Open%20Data%20Telangana%22%2C%22value%22%3A%22Open%20Data%20Telangana%22%7D%5D%7D).
